floooh/sokol

- README.md
- sokol_gfx.h
This is mainly useful for making sokol compatible with applications that need to create multiple GL contexts.
> Support for context switching.

- README.md
- sokol_gfx.h
This implements the new sg_append_buffer() call in sokol_gfx.h discussed here:
https://github.com/floooh/sokol/issues/84
> sokol-gfx: sg_append_buffer() work

- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_time.h
- preparations for MINIMAL_RUNTIME
- closure compatibility
- replace deprecated functions with 'modern' equivalents
> Emscripten platform fixes

- sokol_app.h
Not all Macs support Metal (mine is from 2010 and is stuck on macOS High Sierra 10.13.6) so I brought back GLCORE33 support in sapp like we talked about over Twitter.
What do you think of a check for `__MAC_OS_X_VERSION_MAX_ALLOWED` (https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Using/using.html) to only allow compiling with OpenGL on macOS versions that do not support Metal?
I haven't looked into what all the Cocoa calls do yet (I used the old commit shas you gave me as a reference) so I will not mark this PR as ready until I have had the time to do some research. The branch works on my Mac now anyway :)
> WIP: Bring back glcore33 support in sapp for macOS

- sokol_app.h
Hi,
I was playing around with Sokol app API and while doing some tests I found out, at least on windows, that dpi scaling gets floored because of integer casting operations. In my specific case, the monitor has a scaling of 125%, that is, 1.25, although, because of both `_sapp_win32_content_scale` and `_sapp_win32_window_scale` are declared `int` they will be floored to 1.  I also had to change `_sapp_win32_update_dimensions()` because the first time it is called windows dimensions wouldn't be different, and therefore the framebuffer wouldn't update its dimensions. In a monitor with dpi scaling of 125%, `sapp_dpi_scale()`  would return 1f, while a value of 1.25f is expected.
I don't know whether this was intentional or not. Please have a look at this pull request, it works in my test …
> Win DPI scaling properly taken into account on Windows

- util/sokol_cimgui.h
- util/sokol_gfx_cimgui.h
I'm not sure if you're interested in something like this, but I figured I'd send over a PR and you can either accept it or close it. I converted the sokol Dear ImGui renderer and gfx debugger over to work with cimgui for projects that don't use C++.
> added cimgui wrapper and gfx debugger

- sokol_app.h
https://github.com/floooh/sokol/issues/162
Implemented for Mac. Will look into Linux next and update the pull request as I go.
> Implement key repeat flag.

- sokol_app.h
I need it to access AAssetManager* in my project. Maybe others need it in their projects too.
> Add sapp_android_get_native_activity function

- sokol_audio.h
This is the first working version of the OpenSLES backend that I've added to the sokol_audio.
Obviously, I've ripped most of it from soloud and tried to blend it in with the rest of your code. 
I also implemented a semaphore to wait for buffers instead of soloud's naive implementation (see [here](https://github.com/jarikomppa/soloud/blob/33aeb54b0200fcca15987d539d7a86c5ef086287/src/backend/opensles/soloud_opensles.cpp#L165)).
It's currently working with my test app on android, but it's very sketchy and not tested thoroughly with all scenarios.
Please inform me of any bugs or changes that you may require.
Thanks
> sokol_audio - opensles backend: initial version

- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- sokol_time.h
As per https://github.com/floooh/sokol/issues/205, I've changed `#pragma once` to `ifdef` guards.
Some formatting fixes happened in there. I can re-PR if you don't want them in.
> ifdef guards

- sokol_app.h
Adding support for UTF-8 argv on Windows.
@floooh I'm not sure what's the preference for dealing with unexpected states (OS calls failing), I've used `SOKOL_LOG` for now, but am willing to change to whatever your preference is.
> 141: sokol_app: UTF-8 argv on Windows

- README.md
- sokol_gfx.h
Some cleanup before I want to start a new WebGPU backend:
- merge some duplicate code and data across backends
- better naming for backend-specific structs and functions
- ...?
> [WIP] sokol_gfx.h: some code cleanup in the implementation part

- README.md
Hi, if I understand correctly idea then proposal changes is correct.
> sokol_app.h should be included before sokol_gfx.h

- sokol_gfx.h
> fixing gles2 assertion on shader struct validation

- sokol_app.h
This adds macOS support for sapp_show_mouse().
> Macos show mouse implemented

- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
I actually wrote this last night before posting to Twitter about my stupid C++ trick 🤓
I hope it passes CI!
> reference-based equivalents for c++

- sokol_app.h
Implements sapp_toggle_fullscreen(). Each call changes window style and layout to either windowed or fullscreen based on the value in _sapp.desc.fullscreen.
The code tries to center the window on switch from fullscreen. If the size of the window is too large for the current monitor, it uses the monitor size.
Not sure if you want this or not, but I figured I'll do a pull request. I've only implemented this for win32, can take a look at macOS later if you want to keep it.
I've only tested this under latest Win10.
> sapp_toggle_fullscreen(), implemented for win32

- sokol_app.h
> fullscreen on linux

- sokol_audio.h
> UWP compatibility, no MMDEVICE

- sokol_app.h
Draft with new API per #345. This is tested working on macos and needs to be tested on Windows next.
> Simple drag-n-drop support on macOS and Windows

- README.md
- sokol_app.h
> sokol_app.h: remaining drag'n'drop stuff for HTML5/WASM

- sokol_fetch.h
> Fix range request to not overlap reads

- sokol_app.h
> Fix typo in sokol_app docs

- bindgen/gen_nim.py
* regenerated from sokol/master
* src/ext renamed to src/nim
* `Num` enum constants discarded
> Update sokol-nim and minor changes to gen_nim.py

- sokol_app.h
- util/sokol_debugtext.h
...and some doc-comment improvements.
> Window icon support for sokol_app.h

- sokol_app.h
Like Ctrl, Alt and Super, but for mouse buttons.
> sokol_app.h: add mouse button modifiers

- sokol_fetch.h
The TL;DR instructions should also mention that you need to call sfetch_dowork().
> sokol_fetch docs fix

- CHANGELOG.md
- README.md
- util/sokol_gl.h
> sokol_gl.h: context support

- sokol_app.h
> fixing dpi scale > 2.0 on iOS

- sokol_gfx.h
```sg_draw()``` no longer uses the ```num_instances``` parameter to decide whether the instanced- or non-instanced backend draw function should be used (on D3D11 and GL), instead this is determined by the currently applied pipeline object.
Fixes #596
> sokol_gfx.h: use internal pipeline flag to select instanced draw

- CHANGELOG.md
- README.md
- sokol_app.h
- sokol_time.h
- util/sokol_gfx_imgui.h
- a new function sapp_frame_duration() to get an averaged frame duration in seconds
- 120Hz support on macOS and iOS (query max supported refresh rate)
> sokol_app.h frame timing improvements

- sokol_app.h
For win32 adds per monitor DPI arewareness, so the window's DPI gets updated when it is moved to a monitor with a different DPI. 
- Reverts to system DPI, if an older windows then Windows 10 Creators Update is used
- Although I think this behaviour should be the default, I made it optional for now.  See flag in backend-specific options in app_desc
> sokol_app.h win32: implements optional per monitor DPI awareness

- bindgen/gen_all.py
- bindgen/gen_nim.py
- bindgen/gen_zig.py
* Follow nim code style
* Avoid keyword clashes
* Remove redundant functions, refactor
* Use nim bitfields for some consts
* Generate bindings for sokol_glue.h (I _think_ this makes it possible to use gfx without app)
Corresponding PR for sokol-nim: https://github.com/floooh/sokol-nim/pull/12
> Update Nim bindgen (May 2022)

- bindgen/gen_nim.py
- bindgen/gen_zig.py
- changed directory structure in Nim bindings
- code cleanup both in gen_nim.py and gen_zig.py
- minor naming changes in Nim bindings
> Language bindings generation cleanup round 1

- bindgen/gen_nim.py
- bindgen/gen_zig.py
- the various array converters are now code-generated
- also everything else in the manually written 'extras' source files is now code-generated
- code cleanup and simplifications 
- also some minor code cleanup in the Zig code generator script
> Update Nim bindings generation.

- sokol_gfx.h
As discussed here https://github.com/floooh/sokol/issues/681
> Added sg_query_buffer_will_overflow

- sokol_app.h
> Made Android native activity available before calling sokol_main (#708)

- .github/workflows/gen_bindings.yml
- bindgen/gen_nim.py
- use camel case instead of snake case (these are now Nim warnings)
- enable the bindings generation again, only disable the Windows test (since this fails to build on GH Action, but works fine on my Windows PC).
> Update Nim bindings generation for nim 1.6.8

- .editorconfig
- .github/workflows/gen_bindings.yml
- README.md
- bindgen/.gitignore
- bindgen/gen_all.py
- bindgen/gen_rust.py
> Integrate automatic sokol-rust bindings generation.

- bindgen/gen_zig.py
> Update zig bindgen produce source that matches "zig fmt" style

- CHANGELOG.md
- README.md
- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- util/sokol_debugtext.h
- util/sokol_fontstash.h
- util/sokol_gfx_imgui.h
- util/sokol_gl.h
- util/sokol_imgui.h
- util/sokol_memtrack.h
- util/sokol_nuklear.h
- util/sokol_spine.h
> Rename custom allocator callbacks to alloc_fn/free_fn

- sokol_gfx.h
Moved from https://github.com/floooh/sokol-zig/pull/55
> Allow extensions to load additional GL functions via SG_GL_FUNCS_EXT

- .github/workflows/gen_bindings.yml
This is a port of https://github.com/floooh/sokol-odin/pull/10
> Update Odin to latest build with LLVM17 and enable MacOS again

- sokol_gfx.h
Fix for https://github.com/floooh/sokol/issues/1027
> fix warnings for mingw-w64 toolchain

- CHANGELOG.md
- bindgen/gen_all.py
- bindgen/gen_zig.py
- util/sokol_imgui.h
> Integrate sokol_imgui.h into zig bindings.

- CHANGELOG.md
- README.md
- sokol_gfx.h
See [#1063.](https://github.com/floooh/sokol/issues/1063)
Associated samples PR: https://github.com/floooh/sokol/issues/1063
> Fix sg_update_image() for 3D textures.

- sokol_gfx.h
fixes
https://github.com/floooh/sokol/issues/1071
> logs/ oudated SOKOL_TRACE_HOOKS define

- CHANGELOG.md
- README.md
- sokol_gfx.h
- tests/functional/sokol_gfx_test.c
- tests/functional/sokol_spine_test.c
- util/sokol_fontstash.h
- util/sokol_gfx_imgui.h
- util/sokol_imgui.h
- util/sokol_spine.h
See: https://github.com/floooh/sokol/issues/929
> sokol_gfx.h: remove SG_FILTER_NONE (fixes #929)

- sokol_app.h
Code based on PR #998 and https://github.com/X11-good-tools/x11clipboard.
Handling TARGETS request fixes _sapp_x11_set_clipboard_string() not working on some setups.
Additional minor formatting changes.
Not thrilled about polling or about how much code this all adds, but I don't really see a simpler way of doing this.
> sokol_app: basic x11 clipboard support

- bindgen/gen_jai.py
I saw what was added in https://github.com/floooh/sokol/pull/1176 so i thought i'd do a quick update for the Jai bindgen too :)
> Include comments in Jai bindgen

- bindgen/gen_d.py
cc: @floooh 
- https://github.com/floooh/sokol/pull/1176
- https://github.com/floooh/sokol/pull/1182
> Add comments in D bindgen

- sokol_gfx.h
> sokol_gfx.h gl: better warnings on 'x not found in shader'

- sokol_gfx.h
Adds SG_BLENDOP_MIN/MAX
See #1208 and https://github.com/floooh/sokol-samples/pull/160
> Add SG_BLENDOP_MIN/MAX

- CHANGELOG.md
- sokol_gfx.h
- Fixes https://github.com/floooh/sokol/issues/1217
- Implements https://github.com/floooh/sokol/issues/1218
> D3D11 related regression fixes after compute shader update.

- CHANGELOG.md
- sokol_fetch.h
Ticket: https://github.com/floooh/sokol/issues/1225
(plus some brace-style code cleanup)
> sokol_fetch.h: replace XMLHttpRequest with fetch api.

- sokol_app.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- util/sokol_debugtext.h
- util/sokol_gl.h
- util/sokol_imgui.h
- util/sokol_nuklear.h
- util/sokol_spine.h
...mostly signed-vs-unsigned warnings.
> Fix warnings when compiling with Clang for Windows.

- sokol_gfx.h
> Fix typo in sokol_gfx.h

- .github/workflows/gen_bindings.yml
- bindgen/gen_all.py
- bindgen/gen_d.py
- https://github.com/kassane/sokol-d/pull/80
> gen_d: Add sokol_nuklear and sokol_args support

- sokol_app.h
> sokol_app.h: wait for X11 VisibilityNotify event when mapping window

- bindgen/gen_all.py
- bindgen/gen_d.py
- https://github.com/kassane/sokol-d/pull/85
cc: @floooh
> sokol-d: add `gfx-imgui` support

- .github/workflows/gen_bindings.yml
- bindgen/gen_c3.py
Trying to fix https://github.com/floooh/sokol-c3/issues/4
Related PRs:
- https://github.com/floooh/sokol-tools/pull/191
- https://github.com/floooh/sokol-c3/pull/7
> Change C3 bindgen to generate more idiomatic types

- CHANGELOG.md
- README.md
- sokol_app.h
> sokol_app.h d3d11/dxgi: fix frame time issue on 120Hz displays
