- _sokol_gfx.impl.h
- _sokol_gfx_gl.impl.h
When compiling with fips and vs2015 or vs2017, warnings are errors and switch statements without a default case are warnings.
This change adds a `SOKOL_UNREACHABLE` macro which right now is just defined to `SOKOL_ASSERT(false)`.
> add missing defaults to switch statements

- _sokol_gfx_gl.impl.h
fixes floooh/sokol#29
restoring the state should also restore the VAO that gl backend uses.
> FIX:calling sg_reset_state_cache produces opengl error 0x502

- sokol_app.h
minor cleanup; in my test, I'm including `glcorearb.h` (via gl3w.h) which already defines `WIN32_LEAN_AND_MEAN`
> sokol-app: Win32 preprocessor

- sokol_gfx.h
Since sokol already uses Direct3D11 as a back-end and it's not calling desktop only APIs, it's already UWP compliant; only one issue - UWP apps are meant to only link against `WindowsApp.lib` and nothing else.
Source [here](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-and-com-for-uwp-apps):
> ....Win32 APIs that are part of the UWP and that are implemented by all Windows 10 devices.
> .For convenience, an umbrella library named WindowsApp.lib is provided in the Microsoft Windows Software Development Kit (SDK), which provides the exports for this set of Win32 APIs.
> Link your app with WindowsApp.lib (and no other libraries) to access these APIs.
P.S. Love the idea behind your work and am trying to use it myself. Hence the small fix to make it fully compatible :)
> Conditional including of libs

- sokol_app.h
Not sure if this is the proper solution, but on windows it didn't compile, I guess there are some mouse events that do not carry mouse button, so I added MOUSEBUTTON_NONE for those cases.
> fixed raw mousebutton 0 on some mouse events

- sokol_gfx.h
This should fix compilation issues on ubuntu while linking with mesa/nvidia GLESv2.
P.S. Adding `GLES2/gle2ext.h` will default to Angle extension since it's defined first
Disclaimer:
I didn't test with angle (while extensions are on).
I didn't check with emscripten either.
> Only allow instancing in GLESv2 when the extensions exist

- sokol_app.h
Without these explicit casts there are compilation errors if the implementation file is a C++ unit (.cpp file)
> added explicit casts so impl can be from c++

- README.md
- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_gfx.h
- sokol_time.h
Currently there is no way of using these structs in headers without also including the relevant `sokol_` headers. By giving the public structs and enums names, this is now possible
> Added names to public structs so they can be forward delcared

- README.md
- sokol_gfx.h
This splits the sg_apply_draw_state() function into sg_apply_pipeline() and sg_apply_bindings(), and renames sg_draw_state to sg_bindings (which doesn't have a pipeline member).
Additionally: rename sg_apply_uniform_blocks() to sg_apply_uniforms().
All old functions and structs still exist but are inside an #ifdef SOKOL_NO_DEPRECATED (this can be defined to help with moving old code over).
> sg_apply_pipeline and sg_apply_bindings

- sokol_app.h
Without this explicit cast there is a compilation error if the implementation file is a C++ compilation unit (.cpp file)
> sokol_app.h emscripten: added explicit cast so impl can be from C++

- sokol_gfx.h
This merges all the scattered static variables into the _sg_state_t struct (with the exception of non-POD Objective-C items, these live in a separate struct).
> sokol_gfx.h: merge backend structs

- README.md
- sokol_app.h
This adds the config define SOKOL_NO_ENTRY to sokol_app.h, if this is defined for the implementation, sokol_app.h will not "hijack" the platforms main function, instead the user code must provide this.
TODO:
> sokol_app.h: add an optional "don't hijack main" mode

- README.md
- sokol_app.h
- sokol_audio.h
- new items in sapp_desc and saudio_desc for the optional set of callbacks with user_data
- all callbacks are now optional
- unrelated: added html5_ prefix to some HTML5-platform-specific items
TODO:
> sokol_app.h/sokol_audio.h: userdata support for callbacks

- README.md
- fips.yml
- imgui/README.md
- imgui/sokol_gfx_imgui.h
- sokol_gfx.h
This PR adds optional debugging UI extension headers (or rather: currently only one for sokol_gfx.h called sokol_gfx_imgui.h).
sokol_gfx.h gets a new API function to install callback functions for tracing the public sokol_gfx.h API calls.
TODO:
> Debugging UI extension headers via Dear ImGui

- README.md
- util/sokol_gl.h
This replaced the rudimentary state handling in sokol_gl.h with a "pipeline stack" of proper pipeline-state-objects.
> Pipeline stack for sokol_gl.h

- README.md
- sokol_gfx.h
- util/sokol_gfx_imgui.h
- util/sokol_gl.h
- util/sokol_imgui.h
...makes a lot more sense, especially with the upcoming shader code-generation.
> Move vertex-attr names/semantics from sg_pipeline_desc to sg_shader_desc

- util/sokol_gfx_imgui.h
... when compiled with IMGUI_DISABLE_OBSOLETE_FUNCTIONS
> sokol_gfx_imgui.h: fix use of deprecated ImGui enums

- README.md
- sokol_gfx.h
This removes the 'linker stub' for d3dcompiler_47.dll, instead the shader compiler DLL will now be loaded on demand in the D3D11 backend when the first shader with HLSL source code is created.
> Remove need for SOKOL_D3D11_SHADER_COMPILER

- sokol_app.h
Pretty self explanatory. Thanks. :D
> SAPP_KEYCODE_KP_5 was not implemented on Linux.

- README.md
- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_gfx.h
- sokol_time.h
- util/sokol_cimgui.h
- util/sokol_gfx_cimgui.h
- util/sokol_gfx_imgui.h
- util/sokol_gl.h
- util/sokol_imgui.h
On Windows, this adds __declspec(dllexport) or __declspec(dllimport) to all function declarations so that the sokol headers can be compiled into a DLL.
Fixes #160 .
> Add SOKOL_DLL support to all headers.

- sokol_app.h
This adds a new event and functions to implement 'programmatic quit' to sokol_app.h:
- allow to intercept a pending quit via window close button or "Alt-F4" (e.g to pop up a "Really quit? Yes/No" dialog box)
- request a "soft quit" (same as clicking the window close button)
- order a "hard quit"
One new event and 3 new functions:
- ```SAPP_EVENTTYPE_QUIT_REQUESTED```: This will be sent when the user clicks the window close button, or calls the new function ```sapp_request_quit()```. If the event isn't handled, the application will quit as usual. If the quit should be intercepted, the event handling code must call the new function ```sapp_deny_quit()```.
- ```sapp_request_quit()```: The user code can call this function at any time to initiate a "soft quit" (causing the event …
> Programmatic quit for sokol_app.h

- sokol_audio.h
Fixes this warning:
In file included from sokol-samples\libs\sokol\sokol.c:12:0:
sokol/sokol_audio.h: In function 'bool _saudio_backend_init()':
sokol/sokol_audio.h:1201:1: warning: jump to label 'error' [-fpermissive]
error:
^~~~~
sokol/sokol_audio.h:1127:14: note:   from here
goto error;
^~~~~
sokol/sokol_audio.h:1160:20: note:   crosses initialization of 'REFERENCE_TIME dur'
REFERENCE_TIME dur = (REFERENCE_TIME)
> FIX: warning: jump to label 'error' crosses initialization of 'REFERENCE_TIME dur'

- README.md
- sokol_fetch.h
This fixes the wrong assumption in sokol_fetch.h that it is possible to query the uncompressed file size via the HTTP protocol before downloading an entire file (the response header Content-Length contains the compressed size).
> sokol_fetch.h rework

- sokol_time.h
... okay so I know from testing that this _works_. I'm not convinced this is actually a good idea though (especially supporting a specific microcontroller in the upstream library), especially because if someone really wants to use this they can just do
```
#define SOKOL_IMPL
#define CLOCK_MONOTONIC 0
#include <sokol_time.h>
```
in the implementation file.
... feel completely free to not merge this. I'm completely unconvinced this is a good idea, but, I mean, it works? I think? Like, 99% sure.
> sokol_time: Support the ESP8266 embedded hardware

- README.md
- sokol_app.h
- sokol_gfx.h
- util/sokol_gfx_imgui.h
- new sg_features item: image_clamp_to_border
- new UV wrap mode: SG_WRAP_CLAMP_TO_BORDER
- new enum: sg_border_color with 3 hardwired border colors (transparent, black, white)
- new sg_image_desc item: sg_border_color border_color
Only works in GLCORE33, METAL_MACOS and D3D11.
> Implement clamp-to-border color as optional feature.

- sokol_app.h
Implementing [issue 208](https://github.com/floooh/sokol/issues/208) for Windows:
- Showing and hiding mouse cursor with `sapp_show_mouse(bool)`.
- Querying mouse visibility with `bool sapp_mouse_shown()`.
> 208: sokol_app: Show/hide mouse cursor

- sokol_gfx.h
Added `SG_VERTEXFORMAT_USHORT2N` and `SG_VERTEXFORMAT_USHORT4N`
I don't have the ability to test these across all platforms atm, but I think they should work.
https://docs.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format
https://developer.apple.com/documentation/metal/mtlvertexformat?changes=latest__3_3_1&language=objc
> support 16-bit unsigned normalized vertex formats

- sokol_app.h
1. Added `#pragma comment (linker, "/subsystem:windows")` to avoid having to specify this on the command line (works with cl.exe and clang)
2. Added `#pragma comment (lib, "user32.lib")` for both `SOKOL_D3D11` and `SOKOL_GLCORE33`
3. Added `#pragma comment (lib, "gdi32.lib")` for `SOKOL_GLCORE33`
> [sokol_app.h] Windows linker/lib pragmas for command line compilation

- sokol_gfx.h
This fixes the following warnings when compiling with `-DNDEBUG -Wall -Wextra` on clang:
```
../sokol_gfx.h:5898:61: warning: unused parameter 'pip' [-Wunused-parameter]
_SOKOL_PRIVATE void _sg_gl_destroy_pipeline(_sg_pipeline_t* pip) {
^
../sokol_gfx.h:13394:76: warning: unused parameter 'trace_hooks' [-Wunused-parameter]
SOKOL_API_IMPL sg_trace_hooks sg_install_trace_hooks(const sg_trace_hooks* trace_hooks) {
^
../sokol_gfx.h:14021:53: warning: unused parameter 'name' [-Wunused-parameter]
SOKOL_API_IMPL void sg_push_debug_group(const char* name) {
```
> Fix unused warnings when compiling with NDEBUG

- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- sokol_time.h
- util/sokol_gfx_imgui.h
- util/sokol_imgui.h
This fix the following warnings when compiling with D3D11 backend with mingw-w64 with `-DNDEBUG -Wall`
```
In file included from sample_common.h:11,
from sample-bench.c:1:
../sokol_gfx.h:2474: warning: ignoring ‘#pragma comment ’ [-Wunknown-pragmas]
2474 |     #pragma comment (lib, "user32.lib")
| 
../sokol_gfx.h:2475: warning: ignoring ‘#pragma comment ’ [-Wunknown-pragmas]
2475 |     #pragma comment (lib, "dxgi.lib")
| 
../sokol_gfx.h:2476: warning: ignoring ‘#pragma comment ’ [-Wunknown-pragmas]
2476 |     #pragma comment (lib, "d3d11.lib")
| 
../sokol_gfx.h:2477: warning: ignoring ‘#pragma comment ’ [-Wunknown-pragmas]
2477 |     #pragma comment (lib, "dxguid.lib")
| 
In file included from sample_common.h:11,
from sample-bench.c:1:
../sokol_gfx.h: In function ‘_sg_d3d11_init_caps’: …
```
> sokol_gfx: fix unused warnings in D3D11 code path

- sokol_app.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
Just some minor cleanup.  Curious how you feel about `NOMINMAX`.  Seems important to me because without it, `<windows.h>` stomps any variant of `min()`, and `max()` with a macro.
> added `#define NOMINMAX`, removed redundant `#include <windows.h>`

- sokol_gfx.h
I was doing some benchmarks and noticed by tracing all GL calls that `glDepthMask` and `glStencilMask` is called twice every frame even though I do not use them at all. So this commit skip calling then when the depth/stencil action is `SG_ACTION_DONTCARE` in `_sg_gl_begin_pass`.  This effectively removes any call to both functions on my tests.
> sokol_gfx: skip unecessary GL calls when we don't care about depth/stencil buffer

- sokol_app.h
- sokol_gfx.h
- util/sokol_gfx_imgui.h
glUniform calls are part of the GL shader state, so the link between a texture's uniform location and GL texture slot can be done upfront when creating the shader instead of the resource binding update.
> Move GL texture binding glUniform1i() call into _sg_gl_create_shader()

- sokol_gfx.h
This is an optimization on GL backend to avoid redundant calls to glActiveTexture when binding different textures. This slightly improves my FPS on my benchmark tests with sokol_gfx using GLCORE33. As pointed in #308
> sokol_gfx: cache active textures on GL backend

- sokol_gfx.h
This cache redundant calls to `glUseProgram` when actually no program has changed in the GL state. This happens often in my use case because I execute the same shader often but in a separate pipeline with different blend mode, while the shader (and GL program) doesn't change. And from my benchmarks `glUseProgram` is expansive relative to other calls, look the table in this screenshot as reference, look it can take over ~10000ns while other calls is much less expensive like `glUniform`.
Notice `glUseProgram` is called three times with the same value, this commit omit this uneeded calls.
> sokol_gfx: cache current program in GL backend

- sokol_app.h
Very minor tweak: A dpi of exactly 1.5 is fairly common and I think it should be considered a high dpi screen? Most 4k screens run at 150% in Win10 for instance.
> include dpi scale 1.5 in high dpi

- README.md
- sokol_app.h
- sokol_gfx.h
Move things around a bit internally to be more consistent with how the implementation block in sokol_gfx.h is structured.
> sokol_app.h internal code cleanup

- sokol_fetch.h
Instead of waiting on the event as it's supposed to `_sfetch_thread_dequeue_incoming()` spins while waiting as the address of the event handle is passed to `WaitForSingleObject()` instead of the handle itself causing the function fail immediately as the handle is invalid.
> Fix sokol_fetch.h spinning on Windows

- sokol_app.h
For getting unrestricted mouse-movement information.
Two new functions:
```c
void sapp_lock_mouse(bool b);
bool sapp_mouse_locked(void);
```
When mouse-lock is active, the mouse pointer is hidden, the mouse position reported in SAPP_EVENTTYPE_MOUSE_MOVE appears frozen, and the new sapp_event items mouse_dx/dy contain relative mouse movement.
It is not guaranteed that mouse movement has the same "trajectory" in lock mode (because on some platforms, the "raw mouse movement" APIs are used). In locked mode, MOUSE_MOVE events will also be generated when the mouse leaves the window area or hits the screen border.
If mouse-lock is inactive, mouse_dx/dy will be computed by subtracting the new mouse position from the previous. 
Implementation status:
...this PR also contains the missing …
> sokol_app.h: initial mouse-lock implementation

- sokol_audio.h
Currently using `SOKOL_DUMMY_BACKEND` still includes platform-specific headers. For example I couldn't build the dummy backend on a Linux server without ALSA libraries installed. This PR adds more `#if defined(SOKOL_DUMMY_BACKEND)` checks to skip including headers and defines a dummy mutex as well.
Empty structs have a dummy variable as some MSVC versions can't handle empty structs when compiling in C mode. I also added a dummy variable to the existing empty `_saudio_mutex_t` struct for that reason.
> sokol_audio: Don't include platform headers if SOKOL_DUMMY_BACKEND is defined

- sokol_gfx.h
I just finished successfully integrating sokol_gfx into my personal code (excellent library you've made here!), and it all went extremely smoothly. Except for one hiccup I was stuck on for about 6 hours today.
There is a small piece of the `sg_buffer` API that was confusing, namely the return value from `sg_append_buffer` and how it needs to be set on `sg_bindings::vertex_buffer_offsets[0]`, along with `sg_bindings::index_buffer`. The imgui-d3d11.cc sample file in the sokol-samples has a nice example of how to do this. I was convinced I had been setting up this offset value incorrectly, however, it was a red herring. The real bug in my integration was that when moving from DirectX 9 to DirectX11 the draw primitive function went from counting the number primitives (in my case triangles) to …
> Update docs concerning sg_draw

- README.md
- sokol_app.h
- sokol_gfx.h
This selects either the D3D11 C-API (as before) or the D3D11 C++ API based on whether the sokol_gfx.h implementation is included in a C or C++ file. This is mainly as preparation for https://github.com/floooh/sokol/pull/351
Needs more testing before merge.
Note to self: Should the sokol_app.h Win32 D3D11 backend get the same treatment before merge? It's not strictly needed for UWP, since that has its own backend, but it would be more consistent.
(Answer: definitely yes, otherwise the d3d11.h header would collide if both sokol_app.h and sokol_gfx.h are included together in the same C++ file).
> sokol_gfx.h D3D11 backend: use D3D11 C++ API if impl compiled as C++

- sokol_app.h
Implemented `sokol_app` for UWP.
Added supported features in table: basically close to parity to desktop Win32 (clipboard and cursor capture/replacement only missing). Hopefully this can do for a start :)
Tested and working on my PC and Xbox One via project [here](https://github.com/Aftnet/sokol_app_uwp)
> sokol_app UWP implementation

- sokol_app.h
This is a very early phase. I don't know want what kind of API you want. Probably one function `sapp_set_title(const char* title)`?
I'll add Windows and Linux a bit later.
Also, does Sokol plan to support multiple windows? Right now all functions seem to be using a global main window.
> set window title on macos

- README.md
- sokol_app.h
- in Win32 backend: use DXGI_SWAP_EFFECT_FLIP_DISCARD if possible (when running on Win10)
- in UWP backend: add MSAA support to swapchain code
In both backends: if MSAA is requested, a separate MSAA texture and render-target-view is created, rendering goes into the MSAA render target, and before presentation the MSAA texture is resolved into the non-MSAA swapchain texture.
> sokol_app.h: modernize D3D11 swapchain code

- sokol_gfx.h
I've added the following two functions:
Added sg_mtl_device() for retrieving the metal device
Added sg_d3d11_device() for retrieving the d3d11 device
I have several libraries, one of which (the app framework library) creates these devices. Another library is dedicated to video playback and doesn't have direct visibility of the app framework library, but does need access to the devices for hardware accelerated decoding.
Since the precedent appears to have already been set with the sg_mtl_render_command_encoder() I have added the above two functions to the same section.
> Added sg_xxx_device() for retrieving metal/d3d11 device

- sokol_args.h
Basically just removed all ifdefs disabling parsing of argc/argv in emscripten build.
> sokol_args.h: also parse argc/argv in emscripten build

- sokol_gfx.h
This added an additional field where the target can be specified for an injected GL texture.
I needed this so I can pass an Android GL_OES_EGL_image_external that has been provided by the mediacodec hardware video decode system through sokol and be rendered on the screen using samplerExternalOES. This is achieved by setting this new gl_texture_target field to GL_TEXTURE_EXTERNAL_OES.
> Added gl_texture_target option for injected gl textures

- sokol_gfx.h
There is a small typo in sokol_gfx.h.
Should read `simultaneously` rather than `simultanously`.
> docs: fix simple typo, simultanously -> simultaneously

- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- sokol_glue.h
- sokol_time.h
- util/sokol_debugtext.h
- util/sokol_fontstash.h
- util/sokol_gfx_imgui.h
- util/sokol_gl.h
- util/sokol_imgui.h
- util/sokol_memtrack.h
- util/sokol_shape.h
This was generated by the following ruby script:
```ruby
SDECL = 'SOKOL_API_DECL'
def process_file(fname)
lines = File.readlines(fname)
lines.find { |line|
line =~ /^#if.* SOKOL_([A-Z]_+)_INCLUDED/
}
ldecl = "SOKOL_#{$1}_API_DECL"
decl_line = lines.index { |line|
line =~ /^#if.* #{SDECL}/
}
return if !decl_line
lines.map! { |line|
line.
gsub("#{SDECL}" + ' ' * (ldecl.length - SDECL.length), ldecl).
gsub(SDECL, ldecl)
}
lines[decl_line, 0] = <<~EOF
#if defined(#{SDECL}) && !defined(#{ldecl})
#define #{ldecl} #{SDECL}
#endif
EOF
File.write(fname, lines.join)
end
Dir['**/*.h'].each do |f|
process_file f
end
```
> Auto-generated distinct macros per lib. Resolves #428

- sokol_gfx.h
These are the equivalent to the sg_alloc/init functions and allow async destruction of resources. This is useful when using sokol in a multithreaded scenario; the render thread does the sg_init/sg_uninit while a separate resource/api/update thread can call the sg_alloc/sg_dealloc.
> Added sg_dealloc_xxx() and sg_uninit_xxx() suite of functions

- sokol_app.h
- sokol_fetch.h
- sokol_gfx.h
- util/sokol_gfx_imgui.h
API fixes in sokol_gfx.h and sokol_app.h for automatic language bindings generation (removal of nested anonymous unions and expressions in enums).
> bindgen preparations

- sokol_app.h
> sokol_app.h: trigger a linker error if users forget -pthread

- sokol_app.h
- sokol_gfx.h
Fixes C4191 ("'type cast': unsafe conversion from 'FARPROC' to '...'") when compiled with Visual C++ /W3 or above. The warning appears to be C++ only, so the sokol samples don't complain.
> fix MSVC warnings

- sokol_app.h
- sokol_audio.h
- sokol_gfx.h
The tcc ([Tiny C Compiler](https://bellard.org/tcc/)) linker does not like the `.lib` suffix inside `#pragma comment (lib, "foo.lib")` directives - it fails with `tcc: error: library 'foo.lib' not found` errors. Removing the extension fixes tcc, and all major compilers (msvc/clang/gcc/mingw) compile fine without it, so this change should simply allow the headers to be compiled with a different compiler.
We've needed to, (and have been making) this change over at [vlang/v](https://github.com/vlang/v/tree/master/thirdparty/sokol),  ever since tcc became an officially-supported (and later on, the default for debug builds) C compiler on windows. However, every time we update the headers, we also need to reapply this patch; and we felt that, by PR'ing it upstream, it'd benefit both the V …
> Fix #pragma compilation with tcc on windows

- sokol_gfx.h
`sg_pass_action* actions` → `sg_pass_action* action`
> Fix typos in sokol_gfx.h docs

- sokol_app.h
This addresses #479 enough to get sokol_app.h building and working on macOS 10.12, but it simply disables the drag and drop functionality instead of reimplementing it. It uses a preprocessor guard that checks for 10.13 or greater.
> Fix sokol_app.h not building on macOS 10.12

- sokol_app.h
Prior to this patch, `_sapp_macos_update_mouse()` used `[window mouseLocationOutsideOfEventStream]` to get the mouse position. `mouseLocationOutsideOfEventStream` seems to often lag behind the position of the mouse in the application's windows as reported by incoming mouse `NSEvent`s.
Because the old code before this commit only called `_sapp_macos_update_mouse()` right before `_sapp_frame()`, the individual `mouseMoved:`, `mouseDragged:`, etc. methods on the `_sapp_macos_view` class, which are the only entry points for calling `_sapp_macos_mouse_event()` to send the mouse data to the user application, would be sending the mouse position data that was returned by `_sapp_macos_update_mouse()`, not by the event in the incoming `NSEvent`.
Let's review what this looks like:
* …
> Improve macOS mouse latency and stale positioning

- sokol_gfx.h
C4202 => nonstandard extension used : '...': prototype parameter in name list illegal
[https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4202?view=msvc-160]
C4204 => VS2015: nonstandard extension used: non-constant aggregate initializer
[https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4204?view=msvc-160]
> fix: wrong disable of msvc warning based on comment and commit details

- bindgen/gen_nim.py
- bindgen/gen_zig.py
* Updated gen_nim.py and gen_zig.py to use sokol_gfx.c and sokol_app.c instead of sokol_app_gfx.c
* Fixed gen_nim.py conversion of `const char*` to `cstring` for function arguments
> Updated gen_nim.py and gen_zig.py

- sokol_audio.h
sokol_audio.h on macOS now doesn't include AudioToolbox.h, but instead embeds the required declarations directly. Apart from working around an issue in current Zig 0.8.0 (see https://github.com/ziglang/zig/issues/8360), this is also an experiment to see whether this approach makes sense for getting rid of all system header includes in the future (mainly to simplify cross-compiling, and maybe even to get rid of Objective-C code and instead use generated C bindings for macOS ObC APIs).
> sokol_audio.h macOS: don't include macOS framework headers by default.

- util/sokol_imgui.h
Just a minor fix - global variables were renamed a while ago, but I guess nobody was crazy enough to try compiling with SOKOL_DUMMY_BACKEND. ;)
> sokol_imgui.h: fix compile if built with SOKOL_DUMMY_BACKEND

- sokol_app.h
On MacOS 10.14.6, after implementing a quit menu item (seen in pull request #362) and subsequently additional menu items, I found that upon initial App launch the Apple menu and the App's menus in the main menu bar do not respond to mouse clicks. Switching away from the App and then back again resolves the issue.
I found others having the same issue (MacOS 10.15, using Swift) on stack overflow along with a fix: (https://stackoverflow.com/questions/62739862/why-doesnt-activateignoringotherapps-enable-the-menu-bar). Moving the App activation into the function applicationDidFinishLaunching() seems to work great, after this change, the menus are clickable from first launch.
> MacOS main menu bar activation fix.

- bindgen/gen_zig.py
These changes are required for zig master and are also valid for the latest stable version 0.8.0
> Update gen_zig to support 0.8.0 and master

- sokol_gfx.h
The following pattern will result in `sokol_gfx` failing to apply its changes to OpenGL state:
```c
sg_uninit_pipeline(pip);
// <... any amount of code, *except* sg_apply_pipeline ...>
sg_init_pipeline(pip, &(sg_pipeline_desc){...});
sg_apply_pipeline(pip); // BUG: actually a no-op, and leaves state unchanged
```
It only happens if *both* of the following conditions hold:
1. The uninited pipeline was the last-applied pipeline.
2. No other call to `sg_apply_pipeline` was made in-between.
The problem is that the following branch will be `false` in `_sg_gl_apply_pipeline` (due to pipeline ID reuse), short-circuiting the entirety of the function; thus, the new pipeline will not actually be applied:
```c
if ((_sg.gl.cache.cur_pipeline != pip) || (_sg.gl.cache.cur_pipeline_id.id != …
```
> Fix: sg_uninit_pipeline / sg_init_pipeline pair does not work reliably in OpenGL

- sokol_app.h
I discovered this while experimenting with adding a new language to the bindgen
> Fix `sapp_mouse_shown` function signature

- sokol_gfx.h
Currently, some D3D11 APIs that create resources like a texture may fail in the following scenarios:
* GPU device has been removed
* GPU driver has been updated
* GPU is out of memory
The Sokol GFX code does not check if these functions fail, instead `SOKOL_ASSERT` is used for example in the result of `_sg_d3d11_CreateTexture2D`, however it's better to be able to detect the fail to be able to recover from such situations. For example, it is not uncommon to have computers where the GPU device is removed shortly due to change of power state of a laptop like battery energy saving (where the laptop switches from dedicated GPU card to integrated GPU card) or a GPU driver being updated. In this case failure proof applications will recover from that error by checking at swap phase if D3D11 …
> Check D3D11 calls failures

- util/sokol_imgui.h
sokol_imgui.h wasn't using ```ImDrawCmd::IdxOffset```, causing visual gliches with Dear ImGui v1.86.
Several backends had the same bug. The release notes explain the bug and its fix:
https://github.com/ocornut/imgui/releases/tag/v1.86
I cast the value to ```int``` to be consistent with the rest of the code.
> sokol_imgui.h: use ImDrawCmd::IdxOffset

- CHANGELOG.md
- README.md
- sokol_gfx.h
- util/sokol_gfx_imgui.h
- new uniform types (only relevant for GL backends):
- SG_UNIFORMTYPE_INT
- SG_UNIFORMTYPE_INT2
- SG_UNIFORMTYPE_INT3
- SG_UNIFORMTYPE_INT4
- a new enum sg_uniform_layout (native or std140) used in sg_shader_uniform_block_desc to hint sokol-gfx about the memory layout of uniform blocks (also only relevant for GL backends)
- tighter validation of uniform block interior (only GL backend)
> Support integer uniform types

- sokol_gfx.h
I had a little trouble recently upgrading from sokol_gfx @ bfc41f3f13710f7fc50989215fb844a24466d9bb to aaf2c33278d047404ca434d38804a9e84bb9eda2, as the UB layouts introduced no longer match the expected size and layout for a native GLES2 shader when a float array is used (or any other sub-16-byte primitive array.) IIUC there is just an unhandled case, so I tried to handle it.
> Array uniforms should respect SG_UNIFORMLAYOUT_NATIVE

- CHANGELOG.md
- util/sokol_imgui.h
- input code has been rewritten to use the new evented IO and extended virtual key codes in Dear ImGui
- on non-Emscripten platforms, mouse buttons are no longer "cancelled" when the mouse leaves the screen (since the native desktop platforms automatically capture the mouse when mouse buttons are pressed)
- ```simgui_desc.disable_hotkeys``` has been removed (this is used in https://github.com/floooh/v6502r, don't know yet how to handle this with the new Dear ImGui input system, I may need to add this back somehow)
> sokol_imgui.h: updates for Dear ImGui v1.87

- sokol_app.h
When switching from fullscreen back to windowed mode, the window position is restored incorrectly *if* the monitor's left/top doesn't match 0/0.
Steps to reproduce:
- move window to second monitor (in my case, `mr.left < 0`)
- switch to fullscreen and back
- observe window position different to before, and even outside of visible area if I move it to `x==mr.left`
> sokol_app.h: fix window position after fullscreen toggle

- CHANGELOG.md
- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- util/sokol_debugtext.h
- util/sokol_fontstash.h
- util/sokol_gfx_imgui.h
- util/sokol_gl.h
- util/sokol_imgui.h
- util/sokol_memtrack.h
Each header gets a new ```allocator``` struct item in its setup desc struct, with function pointers to ~~malloc/free compatible~~ alloc/free functions which look similar like malloc/free, but have an additional user_data pointer arg.
TODO:
~~Note that sokol_fontstash.h is special, this will only get the new macros, but no dynamic allocator (because of the way sokol_fontstash.h integrates with fontstash.h)~~
> Add 'dynamic' allocator functions to sokol headers.

- README.md
This is a really minor one-liner but it points the status badge and links for branches and forks to the desired place (and not back to the main repo). In the screenshot here you'll see the URL is going to my fork from the relative URL:
(I'm not sure this is documented anywhere, BTW)
> Change GH badges to use relative URLs

- util/sokol_imgui.h
**Bug:** clipboard pasting doesn't work on Windows
**Fix:** change order of event simulation by releasing the V key BEFORE releasing the modifier (CTRL/Cmd) key.
Tested on:
1. Windows 10 21H2 Build 19044.1706
2. MacOS 12.4 Monterey
> fix(imgui): clipboard paste didn't work on Windows

- util/sokol_imgui.h
This allows ImGui draw ops to write their alpha values to the framebuffer.
This is nice for when you draw Imgui into one buffer that you later want to blit over the rest of your screen, or similarly if you're drawing with two separate MtkViews with Metal and have one transparently layered over the other.
I ran into a case where I was clearing the frame buffer to fully transparent, drawing imgui onto it and then blitting that framebuffer elsewhere. It was showing up fully transparent (no imgui content visible) because imgui is drawing with no alpha write mask.
> Write alpha for ImGui draw ops.

- sokol_app.h
Minor change, switching from int cast to `roundf` and reusing the float intermediate instead of roundtripping through int.
For a window with 850 logical width and 1.75 dpi scale, client rect is 1487px wide. Dividing it back results in window_width of 849.71.
Current logic truncates it to 849 and sets fb_width to 1485px, making it misaligned with the client rect.
After this change window_width is rounded to 850 and fb_width is back to 1487px.
> sokol_app.h win32: Calculate hidpi framebuffer size more precisely

- CHANGELOG.md
- README.md
- sokol_app.h
- sokol_args.h
Emscripten has 'deprecated' the ```ccall()``` Javascript helper function (this is now part of the 'legacy runtime' and causes linker errors. Instead of ccall, sokol_app.h and sokol_args.h now use a lower level set of JS helper functions for string argument marshalling.
> Fixes for Emscripten 3.21

- sokol_app.h
This allows Linux to use EGL instead of GLX.  GLCORE33, GLES2, and GLES3 are supported.
SOKOL_GLES2/3 will select EGL by default.  SOKOL_GLCORE33 defautls to GLX unless SOKOL_FORCE_EGL is defined.
Tested on Intel Adler Lake and Raspberry Pi 4.
> Linux EGL and GLES2/3 support

- sokol_app.h
This makes it possible to differentiate between different types of touch input.
See: https://developer.android.com/ndk/reference/group/input#amotionevent_gettooltype for the documentation of this function
I've tested it and it successfully showed 1 for finger input and 2 for S-Pen input.
I'm unsure if adding a new field to the event struct is the way to go; maybe we should provide the user directly with the `AMotionEvent` and the `pointer_index` (`e` and `idx` variables) instead so that they can then use arbitrary NDK functions in their callbacks.
> sokol_app.h: add a `tool_type` field to the `sapp_touchpoint` struct (valid on Android)

- CHANGELOG.md
- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- use the new EM_JS_DEPS() macro to declare 'indirect JS library dependencies'.
- fix a couple of those new Closure compiler warnings
- sokol_audio.h: remove webkitAudioContext fallback
> Fixes for Emscripten SDK 3.1.24

- bindgen/gen_odin.py
With Odin's new support for `#by_ptr` to represent const references for bindings, we can now generate the bindings without wrapper procs by also using `link_prefix` for the foreign block. I also made the changes to use `c.int` where sokol uses `int` in the C headers to be more idiomatic.
A few of the example programs in `sokol-odin` will need to be updated to remove casts to `int` once this is merged.
> Remove wrapper procs for Odin bindings. Use c.int type

- sokol_gfx.h
Support for the SG_PIXELFORMAT_RGB9E5 texture format is added.
It is widely used to store HDR textures in a memory efficient manner
The format support has not been added to the WebGPU backend since the WGPUTextureFormat_RGB9E5Ufloat constant is not available in the webgpu headers used in the current WebGPU backend implementation (the feature was introduced a bit later, gpuweb/gpuweb#975). The support can be added right after #657 is completed.
> Add RGB9_E5 texture format

- sokol_app.h
- sokol_args.h
- sokol_audio.h
- sokol_fetch.h
- sokol_gfx.h
- util/sokol_debugtext.h
- util/sokol_fontstash.h
- util/sokol_gl.h
Removes SOKOL_LOG from sokol_fontstash.h and sokol_args.h entirely because it's not used there.
Please note that merging this as-is will break the binding repos for windows because they do `#define SOKOL_LOG(msg) OutputDebugStringA(msg)`. Here it is for sokol-zig:
https://github.com/floooh/sokol-zig/blob/2bd3b4f44ae137858dbfd5038db40c40563aa86d/src/sokol/c/sokol_defines.h#L5
This should either be removed, or replaced with something like this:
```c
#define SG_LOG_DEFAULT(msg) { OutputDebugStringA("sg: "); OutputDebugStringA(msg); OutputDebugStringA("\n"); }
#define SAPP_LOG_DEFAULT(msg) { OutputDebugStringA("sapp: "); OutputDebugStringA(msg); OutputDebugStringA("\n"); }
#define SAUDIO_LOG_DEFAULT(msg) { OutputDebugStringA("saudio: "); OutputDebugStringA(msg); OutputDebugStringA("\n"); } …
```
> Replace SOKOL_LOG with runtime callbacks.

- bindgen/README.md
- bindgen/gen_zig.py
This adds compile-time switches to have the generated code be compatible with both stage1 and self-hosted.
The `asRange` change has to do with [the self-hosted compiler not passing structs/arrays by reference in all cases](https://github.com/ziglang/zig/issues/12638#issuecomment-1228824773). 
In debugging why the triangle example wasn't rendering, the GL state showed that the gpu-side buffer was filled with bad data (ie. not the verts specified in the source). Upon further inspection, even though the buffer data was being read from the text segment, it was being copied into an array on the stack inside `asRange`, and the ptr to that array was then being returned in the `Range`, and then the data on the stack was getting stomped on the way to the call to upload it to the GPU. 
This does …
> gen_zig.py: add compile time branches for self-hosted support

- CHANGELOG.md
- README.md
- sokol_app.h
- sokol_fetch.h
- tests/CMakeLists.txt
- tests/functional/sokol_fetch_test.c
Same as has happend in other sokol headers already, discrete pointer/size pairs are replaced with a sfetch_range_t ptr/size pair struct. This affects:
- sfetch_request_t: .buffer_ptr/.buffer_size have become .buffer, and .user_data_ptr/.user_data_size have become .user_data
- sfetch_response_t: the .buffer_ptr/.fetched_size (no typo) has become .data, the .buffer_ptr/.buffer_size has become .buffer, and for .fetched_offset has been renamed to .data_offset
- in the function sfetch_bind_buffer() the buffer_ptr/buffer_size args have been merged into a single buffer arg
In sokol_app.h, the HTML5 specific structs sapp_html5_fetch_request and sapp_html5_fetch_response has been updated likewise.
> sokol_fetch.h: replace discrete ptr/size pairs with sfetch_range_t

- CHANGELOG.md
- README.md
- sokol_gfx.h
- tests/functional/sokol_gfx_test.c
- util/sokol_gl.h
- util/sokol_spine.h
Adds the abillity to hook callback functions into sokol-gfx which are called from inside sg_commit(). This is mostly useful for other libraries on top of sokol-gfx to be notified about the end/start of a new frame.
1 new struct and 2 new functions:
- sg_commit_listener: a function pointer / userdata pair
- sg_add_commit_listener
- sg_remove_commit_listener
Also in other headers:
- in sokol_spine.h, the sspine_new_frame() function has been removed
- sokol_gl.h now internally uses a commit listener (no public API changes)
> Commit listener callback in sokol-gfx.

- CHANGELOG.md
- README.md
- util/sokol_gl.h
- util/sokol_spine.h
Same idea as in sokol_spine.h, sokol-gl commands can be recorded into different layers, and those layers can be rendered separately, this allows to mix chunks of sokol-gl rendering with other drawing operations.
TODO:
- ~~[ ] maybe add a separate sample (I have extended the sokol-spine layers sample to also use sokol-gl layered rendering~~ (once sokol_debugtext.h gets render layers too, I'll add a new sample to interleave this with sokol_gl.h)
> Render layer implementation for sokol_gl.h

- CHANGELOG.md
- README.md
- sokol_gfx.h
- tests/functional/sokol_gfx_test.c
- clarify destroy vs uninit vs dealloc behaviour for resources in various resource states
- destroy / uninit / dealloc functions are safe to call for resources in any state, will generally do the right thing, or at most put a warning log message
- uninit functions no longer have return value, instead it's safe to call uninit and dealloc on resources in any state
- new documentation blurb about two-step resource creation/destruction
- some general internal code cleanup and better naming in the resource creation/destruction code
- a new sg_desc.disable_validation boolean to disable the validation layer even in debug mode (useful for unit tests)
- cleanup an old FIXME in sg_create_pass(): creating a pass with invalid images now creates a pass object in FAILED states (assuming that the …
> Clean up sokol-gfx resource creation/destruction code.

- sokol_gfx.h
Noticed a small typo here, updated the docs for you based on what the default enums are
> Typo in docs on pipeline stencil

- util/sokol_imgui.h
The mouse worked fine, because mouse movement events were updated along the way, but touch events do not do that, so imgui was processing button pushes at the previous tap's location resulting in several issues including getting stuck int he dragging window state like this:
https://user-images.githubusercontent.com/55607276/207410919-c7d61bb6-7760-4d10-9fc1-571d8350ef32.mp4
This PR fixes that issue, and likely fixes issues with selecting buttons rapidly with a mouse (for example a macro that teleports the mouse and doesnt generate move events... I don't know if that is likely to happen or not).
> Correct order of mouse/tap events to ImGui for correct touch event handling

- CHANGELOG.md
- README.md
- sokol_gfx.h
Fixes a new Metal validation layer error (the underlying problem might have sporadically caused problems much longer though). For details see: https://github.com/floooh/sokol/issues/762
> sokol_gfx.h metal: use a second cmdbuffer for swapchain resource lifetime management.

- bindgen/gen_zig.py
Now that zig stage1 no longer exists, `meta.FnPtr` was removed since there is only one kind of function pointer syntax now.
> gen_zig.py: update function pointer syntax

- sokol_audio.h
This likely caused an application crash on a system with a buggy audio
system (see https://github.com/mgerdes/Open-Golf/issues/27).
Note that this change is completely untested!
> sokol_audio.h: check more OpenSLES calls during Android audio init

- util/sokol_imgui.h
ImGui 1.89 marked some key modifiers as obsolete; replace
them with newer ones.
> sokol_imgui.h: Fix obsolete key modifier enum usages

- sokol_gfx.h
Fixed minor typos in sokol_gfx.h doc: metal was used instead of d3d11 or wgpu.
> sokol_gfx.h: minor doc fixes (typo, copy-paste)

- sokol_gfx.h
While the Metal backend will accept a larger buffer neither the GL nor the DirectX backend will. By making validation stricter we prevent code developed with the Metal backend from crashing when run on GL or DX.
See e.g. validation for GL: https://github.com/floooh/sokol/blob/b3aecb21825f3191a9a150bc0918fc8c7df7855c/sokol_gfx.h#L7985
Also, it may only crash with validation enabled.
> Align validation with greatest common requirement

- sokol_app.h
- sokol_gfx.h
- util/sokol_gfx_imgui.h
SG_PIXELFORMAT_SRGB8A8 texture format is introduced
This is the first separate part towards full sRGB support, as specified in #562.
The SRGB8A8 format is a non-linear RGB format with linear alpha. This format is the most universal and the most supported sRGB format, with the exception of the compressed DXT family. DXT family is out of scope of this pull request but could be implemented separately. The proposed implementation is supposed to work on all backends except WebGL1 and WGPU
> basic sRGB sampling with SG_PIXELFORMAT_SRGB8A8 format

- sokol_gfx.h
There was a specific problem with the OpenGL backend: despite the API providing support for at least 12(`SG_MAX_SHADERSTAGE_IMAGES`) slots for textures for the vertex shader and 12 for the fragment shader, the OpenGL implementation could bind only SG_MAX_SHADERSTAGE_IMAGES combined for both stages because of the length of the binding cache.
I propose fixing this issue by increasing the cache size to the value of `SG_MAX_SHADERSTAGE_IMAGES * SG_NUM_SHADER_STAGES` so that all images can be bound. The actual number of supported images is known at runtime, `_sg.gl.max_combined_texture_image_units`, and is already used to prevent unsupported bindings.
PS: the previous PR #766 could be used to work around these restrictions as well, but that is an independent improvement with its own goal to …
> OpenGL: two stage texture binding bug

- sokol_audio.h
Required by a `snd_pcm_hw_params_alloca` call in `_saudio_alsa_backend_init`.
This change makes it so the implementation links correctly on Linux in `-std=c99` mode, instead of relying on implicit `alloca` only provided by GNU extensions.
> sokol_audio.h: Include alloca.h on Linux

- CHANGELOG.md
- README.md
- sokol_gfx.h
- tests/functional/sokol_gfx_test.c
Adds a set of functions for obtaining a (more or less complete) ```sg_*_desc``` struct of an existing resource. The structs may only be partially filled, any parameters which have not been kept around internally will be zeroed (but anything except sg_shader_desc structs is quite complete).
Related to issue https://github.com/floooh/sokol/issues/568
> sokol_gfx.h: add sg_query_[buffer|image|shader|pipeline|pass]_desc() functions.

- sokol_gfx.h
Fix warning C4113: 'PFN_glTexParameterfv' differs in parameter lists from 'PFNGLTEXPARAMETERFVPROC'
See https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexParameter.xhtml for reference (third parameter should be `const` qualified).
> Fix warning relating to glTexParameterfv

- .github/workflows/gen_bindings.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/floooh/sokol/actions/runs/4583912323:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
> gh actions: replace unmaintained actions-rs/toolchain action

- sokol_app.h
The MOUSEWHEEL messages provide the mouse position in absolute coordinates, so updating it the same way you respond to other mouse messages is not correct. One solution would be to translate the mouse coordinates to client space, but it's not clear to me why this is being updated here. 
This problem was introduced recently and my application was working fine before it. I can implement a different workaround if the mouse_update call is necessary for reasons that I'm not aware of. For example, we could pass a flag to transform the coordinates when necessary.
> Mouse wheel message is setting invalid mouse position.

- sokol_app.h
In order to detect if any modifier keys are being pressed at the end of a drop event.
> Update event modifiers on drag and drop events.

- CHANGELOG.md
- util/sokol_imgui.h
Dear ImGui 1.89.5 has a new IO function io.AddMouseSourceEvent() which allows to differentiate between mouse- and touch-events, which in turn fixes ui tab selection (this now works with a single tap, previously a double-tap was needed).
> sokol_imgui.h: improve touch input with new Dear ImGui 1.89.5 function.

- .github/workflows/gen_bindings.yml
- bindgen/gen_nim.py
warning:: `unsafeAddr` is a deprecated alias for `addr`
use `addr` instead.
> use addr instead unsafeAddr

- sokol_app.h
it was a typo SOKOL_APP_IMPL -> SOKOL_API_IMPL
> fix public function implementation prefix for egl functions

- util/sokol_debugtext.h
Found a missing `(` in debugtext code example.
> sokol_debugtext.h: fix doc code example typo

- CHANGELOG.md
- README.md
- util/sokol_gfx_imgui.h
- util/sokol_imgui.h
Adds the following to sokol_imgui.h:
- `simgui_image_t` which groups a sokol-gfx image and sampler
- `simgui_image_desc_t` desc struct to create an `simgui_image_t`
- `simgui_make_image()` to create an `simgui_image_t` object
- `simgui_destroy_image()` to destroy an `simgui_image_t` object
- `simgui_imtextureid()` has been changes to take an `simgui_image_t` handle instead of sg_image
- `simgui_desc.image_pool_size`
- `simgui_desc.logger`: added logging support
- allocation failure now results in a log-panic
- added an 'init_cookie' to make sure that API functions are only called between setup/discard
TODO:
> sokol_imgui.h: proper support for user images with samplers.

- CHANGELOG.md
- README.md
- util/sokol_imgui.h
- util/sokol_nuklear.h
Same as https://github.com/floooh/sokol/pull/861, but for sokol_nuklear.h
> sokol_nuklear.h: add support for custom images and samplers.

- .github/workflows/gen_bindings.yml
- CHANGELOG.md
- sokol_gfx.h
See https://github.com/floooh/sokol/issues/872
This does away with the separate retained-reference command buffer for the present call, and instead uses the regular 'deferred release queue' for the default pass MTLRenderPassDescriptor. Since the render-pass-descriptor holds a strong-ref to swapchain surfaces this should make sure that those surfaces outlive their command buffer when they are released by MTKView because of a window resize. This means there's a memory spike during window resize, but I guess there's no way around that.
This also replaces the changes from https://github.com/floooh/sokol/pull/763 with a different approach.
> sokol_gfx.h mtl: new attempt to fix swapchain lifetime issues

- sokol_gfx.h
the framebuffer was getting bound even when msaa hadn't changed it
> fix errant framebuffer bind

- CHANGELOG.md
- README.md
- sokol_gfx.h
> sokol_gfx.h metal: add debug labels and support push/pop debug group

- sokol_gfx.h
Fixes a crash triggered when creating a sg_pass for a sg_image that had an injected GL_TEXTURE_RECTANGLE texture
> take texture target into account when binding to framebuffer

- sokol_gfx.h
This adds the missing error code paths (_SG_ERROR log + put object into SG_RESOURCESTATE_FAILED mode) when Metal object creation fails for the following object types: 
- buffers
- textures
- samplers
- depth-stencil-state (inside sg_make_pipeline())
NOTE: For (Web)GL this isn't possible without involving a full pipeline flush (caused by calling glGetError()), and WebGPU's asynchronous error reporting also doesn't allow to react to out-of-memory-situations at object creation time.
> sokol_gfx.h add missing error paths when backend resource creation calls fail

- CHANGELOG.md
- sokol_args.h
- tests/functional/sokol_args_test.c
See #876.
Key-only args have an empty string as value, and can be checked with `sargs_exists()` or `sargs_boolean()`.
> sokol_args.h: support key-only args

- CHANGELOG.md
- sokol_fetch.h
- tests/functional/sokol_fetch_test.c
This also sets the `finished`, `failed` and `error_code` fields in the response when a request has been cancelled before it was dispatched, also some minor code cleanup around cancelling requests, and adding two more related tests.
> sokol_fetch.h: fix response state when cancelling a request before dispatch (fixes #882)

- CHANGELOG.md
- sokol_gfx.h
Issue: https://github.com/floooh/sokol/issues/905
- fixed compilation of sokol_gfx.h on older macOS SDKs
- fix validation layer error because textures were created with shared-storage-mode, but this isn't supported on Intel Macs
TODO:
> sokol_gfx.h metal: fix Intel Mac compilation and validation layer problems.

- bindgen/gen_rust.py
- bindgen/gen_zig.py
- sokol_gfx.h
fixes #892
There is a simpler fix of adding this function, but I figured you might not want to add backend-specific public apis.
```
void sg_set_default_gl_framebuffer(GLuint framebuffer) {
_sg.gl.cur_context->default_framebuffer = framebuffer;
}
```
This is nicer for the end user than the callback approach, because you don't have to create the callback and a global. and set the global before calling sg_begin_default_pass.
> add callbacks for default gl framebuffer. 

- sokol_app.h
By doing all attribute queries at once it decreases startup time by ~65ms and also makes my binary 1.5kb smaller.
Win10, Nvidia 3070
Tested with code similar to
```c++
static void init_userdata_cb(void* in_app) {
printf("Startup time %f\n", stm_ms(stm_diff(stm_now(), start_ticks)));
}
sapp_desc sokol_main(int argc, char* argv[]) {
stm_setup();
start_ticks = stm_now();
return sapp_desc{
.init_userdata_cb = init_userdata_cb,
}
}
```
> Windows OpenGL startup time optimization

- sokol_gfx.h
Our project had horrible development performance due to all of sokol's `glGetError` calls (that function is super slow in chromium), this PR allows us to disable sokol's gl error checks, while leaving all of sokols asserts enabled for development. At the end of the frame we `assert(glGetError()==0)` as a sanity check. if that assert ever gets triggered, we can re-enable sokol's default `_SG_GL_CHECK_ERROR` definition for debugging
> Allow overriding the gl error check macro

- CHANGELOG.md
- sokol_gfx.h
- explicitly set GL_TEXTURE_MAX_LEVEL in _sg_gl_create_texture()
- more detailed error logging when framebuffer completeness checks fail
TODO:
- add missing GL defines for Windows GL loader
- can we actually remove SG_FILTER_NONE now???
Ticket: https://github.com/floooh/sokol/issues/923
Related:
- https://github.com/floooh/sokol/issues/912
- https://github.com/floooh/sokol/pull/911
> sokol_gfx.h gl: explicitely set GL_TEXTURE_MAX_LEVEL

- CHANGELOG.md
- sokol_gfx.h
Fixes https://github.com/floooh/sokol/issues/931.
Fixes https://github.com/floooh/sokol/issues/930
TODO:
> sokol_gfx.h: expose backend-specific resources and resource injection tweaks

- bindgen/gen_nim.py
related to [this discussion](https://github.com/floooh/sokol-nim/pull/25), this PR adds a simple check that sets NDEBUG when the Nim compiler is called with the release flag
> In nim bindings, set NDEBUG in release mode

- bindgen/gen_nim.py
See [this issue](https://github.com/floooh/sokol-nim/issues/26). This PR fixes the asserts to use `<=`
> Update generated Nim converter asserts

- bindgen/gen_rust.py
See: https://rust-lang.github.io/rust-clippy/master/index.html#/manual_slice_size_calculation
> rust: Fix manual_slice_size_calculation lint.

- sokol_gfx.h
It seems that a typo in enum names prevented Metal buffer updates in Managed mode on Metal backend with a discrete GPU (for example, MBP 2019 16" with AMD graphics). As a result many samples relying on buffer updates wouldn't display anything (i.e. ImGUI, Nuklear, animations etc).
> Fix Managed buffers updates on Metal with discrete GPU

- util/sokol_nuklear.h
This method was recommended by @vurtun: https://github.com/vurtun/nuklear/issues/189#issuecomment-236587263
This is an older comment but the functionality works as expected.
> sokol_nuklear.h: change snk_handle_event to return a bool if handled

- CHANGELOG.md
- README.md
- sokol_app.h
- sokol_gfx.h
- tests/functional/sokol_gfx_test.c
Fixes https://github.com/floooh/sokol/issues/946
Also add public functions `sg_query_row_pitch()` and `sg_query_surface_pitch()` (expose the private functions `_sg_row_pitch()` and `_sg_surface_pitch()` in the public API.
TODO:
> Query pixel format bytes-per-pixel, row- and surface-pitch.

- sokol_app.h
Workaround for the MTKView resizing glitch by "anchoring" the layer to the window corner opposite to the currently manipulated corner (or edge). This prevents the content stretching back and forth during resizing. This is basically this: https://github.com/floooh/sokol/issues/700
As pointed out in the [glitchess resizing](https://thume.ca/2019/06/19/glitchless-metal-window-resizing/) blogpost, `layerContentsPlacement = .topLeft` helps because it prevents stretching the content of the layer while waiting for the correctly sized frame to be rendered. However it works only if the rendered elements are top left aligned. If there are elements that are rendered in the bottom right of the frame and the user resizes from the top left of the window, these elements will appear to shake as they get …
> macOS: workaround wobbly MTKView resizing

- sokol_gfx.h
- util/sokol_gfx_imgui.h
This request is adding support for some broadly used compressed texture formats, which could be very useful with the basis_universal texture transcoding library.
Extended set of "known" formats with SRGB support:
* BC3_SRGBA
* BC7_SRGBA
* ETC2_SRGB8
* ETC2_SRGB8A8
"Brand-new" ASTC format:
* ASTC_4x4_RGBA,
* ASTC_4x4_SRGBA
4x4 subset is selected as the most broadly used [and the only one of ASTC formats that is supported by the transcoding library](https://github.com/BinomialLLC/basis_universal/blob/ad9386a4a1cf2a248f7bbd45f543a7448db15267/transcoder/basisu_transcoder.h#L69C26-L69C26).
> Additional texture pixel formats [BC3, BC7, ETC2 with sRGB, ASTC 4x4]

- sokol_app.h
- tests/functional/sokol_spine_test.c
- util/sokol_gl.h
Need to specify `(void)` as the empty arg list in C rather than just `()`.
> Fix strict-prototype warnings.

- sokol_app.h
If use the `getRawX` `getRawY`  method in multi-window mode on the Android platform, it will not accurately correspond to the touch position of the current window.
> Change getRawX to getX on the Android

- CHANGELOG.md
- README.md
- sokol_app.h
PR for: https://github.com/floooh/sokol/issues/972
This restores the old HTML5 event bubbling behaviour (e.g. most event do not bubble up), but allows to enable bubbling for specific input event categories.
TODO BEFORE:
TODO AFTER:
- merge https://github.com/floooh/chips-test/tree/sapp-event-bubbling
> sokol_app.h emsc: optional event bubbling

- sokol_app.h
Hi, this pr solves the issue [sometimes, on luanch an executable file could not get window focus](https://github.com/floooh/sokol/issues/757).
it has a time interval between app launch and the app fully activated.
the time interval becomes longer when init_cb is slower.
if there are mouse events(e.g. mouse move) during the interval, then app can not be activated and focus will lost even when app launched and order front.
I read some Apple documents and found nothing about this situation.I think maybe it's a bug in Cocoa Appkit.
By the way, GTK also has this problem. And GTK solved it even though they are not 100% sure about the root cause.
see: https://gitlab.gnome.org/GNOME/gtk/-/issues/2342    
As a walkaround, we send a focus event in front of event queue.
> Sokol app focus steal

- util/sokol_debugtext.h
based on D bindings: https://github.com/kassane/sokol-d/issues/5#issuecomment-1921244802
cc: @floooh
> Check isnan Width and Height

- sokol_gfx.h
sokol was invalidating the depth/stencil attachment when there was none attached. Because of this, we were seeing webGL's gl.InvalidateFramebuffer in performance profiles when the call wasn't needed at all.
This PR only clears the depth or stencil attachments if the pass has a depth/stencil attachment.
> skip framebuffer invalidation when possible

- .github/workflows/gen_bindings.yml
- CHANGELOG.md
- README.md
- bindgen/gen_all.py
- bindgen/gen_nim.py
- bindgen/gen_odin.py
- bindgen/gen_rust.py
- bindgen/gen_zig.py
- sokol_app.h
- sokol_gfx.h
- sokol_glue.h
- tests/compile/sokol_gfx_imgui.c
- tests/compile/sokol_gfx_imgui.cc
- tests/compile/sokol_glue.c
- tests/compile/sokol_glue.cc
- tests/functional/CMakeLists.txt
- tests/functional/sokol_debugtext_test.c
- tests/functional/sokol_gfx_test.c
- tests/functional/sokol_log_test.c
- util/sokol_gfx_imgui.h
> Render pass cleanup (implements #904)

- sokol_app.h
Implementation of the idea suggested in https://github.com/floooh/sokol/issues/843#issuecomment-1959114136
`emscripten_set_main_loop` is a higher level function compared to `emscripten_request_animation_frame_loop` and seems to play nicer with various `emcc` options (EXIT_RUNTIME or PROXY_TO_PTHREAD). The downside is that we have to compute the timestamp on our side and hence it might be less accurate than the one the browser returns with `[requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)`.
I tested both implementation on a test app. Not sure if we need more testing and how to test.
In particular for my use case, only the version `SOKOL_EMSC_USE_SET_MAIN_LOOP` works when `PROXY_TO_PTHREAD` is enabled. But A few more changes are needed …
> [sokol_app] add an option html5_use_emsc_set_main_loop

- util/sokol_imgui.h
As a happy sokol_imgui user, I am humbling proposing this PR. It splits the font texture creation in a API function and add a function for the font texture destruction. Those functions are  considered optional function of the imgui backends.
For instance they are implemented for opengl3 on the main imgui repo:
https://github.com/ocornut/imgui/blob/659fb41d0a23efbb9ea6cf74f51ecae0a51575b5/backends/imgui_impl_opengl3.h#L39C1-L42C3
I find those functions are useful in two cases:
- when testing different fonts raterization config,  it is convenient to recreate the texture dynamically. The imgui's author provides an example of such application: https://gist.github.com/ocornut/b3a9ecf13502fd818799a452969649ad
- when creating non default font, this allows to remove the boilerplate of uploading …
> [sokol_imgui] add  the optional backend interface for font management

- util/sokol_imgui.h
Every time you invoke the io->AddFontXXX functions, imgui invalidates the default atlas texture, as it rebuilds the texture packer and needs to reload the new atlas on the GPU.
> fix font loading to work with more fonts than default one

- sokol_gfx.h
I'm not sure why the static string size limit was so low, since it's used for vertex attribute names. I ran into issues where a regular variable name of a shader vertex vertex/instance attribute would trigger this limit.
So I changed it to 32 which seems like a more reasonable limit for variable names...
> [sokol_gfx] Increase _SG_STRING_SIZE from 16 to 32

- bindgen/gen_odin.py
There is no reason to have a `NUM` field at the end of an enum in Odin. Because unlike in C, Odin supports `len(My_Enum)`. And the additional enum field also interferes with things like enumerated arrays and bit_sets.
> [odin bindings] Exclude 'NUM' enum values

- sokol_gfx.h
This change assigns the "label" field form resource desc structs to D3D11 resource objects, using 
`SetPrivateData` with `WKPDID_D3DDebugObjectName`. This code is enabled only when `SOKOL_DEBUG` is defined.
Note: this requires sokol_gfx to also link with `dxguid.lib`.
Note: some resources have multiple "sub-resources", e.g. a shader has a vertex and a fragment shader resource. In those cases the label is the same for all sub-resources.
This is useful especially in RenderDoc ([docs](https://renderdoc.org/docs/how/how_annotate_capture.html#:~:text=tex2d%2D%3ESetPrivateData(WKPDID_D3DDebugObjectName%2C%20sizeof(%22Example%20Texture%22)%2C%20%22Example%20Texture%22)%3B)) and in D3D11 debugging messages.
> [sokol_gfx] Assign labels as debug names to D3D11 resources

- sokol_app.h
Minimal changes to support "NO_API" on windows.
> Adds SOKOL_NOAPI to WIN32

- sokol_gfx.h
Marks R32F, RG32F, and RGBA32F as filterable on wgpu backend by checking feature flag (according to the table here https://gpuweb.github.io/gpuweb/#texture-format-caps). Seems to be OK-widely supported as well (https://web3dsurvey.com/webgpu/features/float32-filterable), though not sure if that's a concern.
> Mark WebGPU 32-bit float texture formats as "filterable" if device supports it

- .github/workflows/gen_bindings.yml
- bindgen/.gitignore
- bindgen/gen_all.py
- bindgen/gen_d.py
Based on `gen_zig.py`.
Result: https://github.com/kassane/sokol-d (unofficial)
**Note:** I will archive my repository if there is interest in official support.
- ~~https://github.com/floooh/sokol-tools/pull/115~~
- https://github.com/floooh/sokol-tools/pull/128
cc: @floooh
> Bindgen: D language

- bindgen/gen_all.py
- bindgen/gen_zig.py
- sokol_fetch.h
Related to this issue: https://github.com/floooh/sokol-zig/issues/63. Not ready to be merged, just thought it might be helpful for that discussion
> Changes to support generating the sokol-fetch bindings in zig

- sokol_audio.h
You do not need to include alloca.h on FreeBSD in order to have the prototype for the alloca function.  It is defined in stdlib.h.
> Fix include to work on FreeBSD

- sokol_app.h
This unusual scancode (`0x136`) appears on my keyboard as a scancode for right shift, instead of the normal `0x36`. 
From MSDN: 
> Indicates whether the key is an extended key, such as the right-hand ALT and CTRL keys that appear on an enhanced 101- or 102-key keyboard. The value is 1 if it is an extended key; otherwise, it is 0.
Even though scancode for right shift already exists.
> Add extra right shift scancode.

- CHANGELOG.md
- README.md
- sokol_gfx.h
Works around a Chrome 127 and Safari Tech Preview regression on macOS which broke sokol-gfx offscreen rendering. The bug is triggered by setting the MAX_TEXTURE_LEVEL, but not calling glTexStorage to allocate storage for immutable textures.
The workaround calls glTexStorage, but currently only on Emscripten.
A proper fix would be to rewrite texture initialization to generally use glTexStorage + glTexSubImage, but this requires a fallback for macOS because GL 4.1 doesn't have the glTexStorage call yet.
Also see #1085 and https://issues.chromium.org/issues/355605685
> sokol_gfx.h gl: implement workaround for Chrome v127 regression

- bindgen/.gitignore
- bindgen/README.md
- bindgen/gen_all.py
- bindgen/gen_jai.py
I've created `gen_jai.py` to support generating Jai bindings, based on the work done in `gen_odin.py`.
Note: right now `gen_all.py` expects a `sokol-jai/` folder to be present so i've added a line to the README with the bindings i'm maintaining [here](https://github.com/colinbellino/sokol-jai), feel free to delete that commit.
> Add Jai bindgen

- bindgen/gen_jai.py
Added missing `,link_always` when using the Metal backend on MacOS, which caused linker issues on some versions of MacOS.
This should fix the following linker error when using Metal:
```console
lld-macos: error: undefined symbol: ___isPlatformVersionAtLeast
```
> Fix Jai bindings for Metal on MacOS

- CHANGELOG.md
- tests/functional/sokol_gl_test.c
- util/sokol_gl.h
Also:
- more detailed error tracking
- two new functions to query number of recorded vertices and commands
Fixes #1092
> sokol_gl.h: don't skip rendering completely in case of errors

- CHANGELOG.md
- sokol_gfx.h
Fixes: https://github.com/floooh/sokol/issues/1043
Basically call `sg_setup()` like this:
```c
sg_setup(&(sg_desc){
.environment = sglue_environment(),
.logger.func = slog_func,
.d3d11_shader_debugging = true,
});
```
...and then just make sure to feed HLSL source code into `sg_make_shader()` instead of bytecode (e.g. when using `sokol-shdc`, omit the `-b / --bytecode` cmdline option.
> sokol_gfx.h d3d11: add sg_desc.d3d11_shader_debugging bool flag

- sokol_app.h
When we use SOKOL_NOAPI the cleanup of the window still was trying to destroy an opengl context.
> Fixes a missing wgl destruction (SOKOL_NOAPI)

- sokol_audio.h
The code path tries to return void. Does not compile for obvious reasons.
> Fix _saudio_backend_shutdown for _SAUDIO_APPLE

- sokol_gfx.h
Page 209 of https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf (and page 181 of https://registry.khronos.org/OpenGL/specs/gl/glspec43.core.pdf for 4.3) show `R11F_G11F_B10F` as color renderable.
> Allow SG_PIXELFORMAT_RG11B10F to be a render target on SOKOL_GLCORE

- util/sokol_imgui.h
This PR brings `sokol_imgui.h` up to date with Dear ImGui v1.91.4 which changes the type of `ImTextureID` from `void*` to `uint64_t`.
> sokol_imgui.h: changed ImTextureID type from void* to uint64_t

- util/sokol_nuklear.h
This adds the cursor to be available for use when using the default font. 
To enable cursors in a sokol application:
- First hide the native mouse: ```sapp_show_mouse(false);```
- Then show the nuklear mouse: ```nk_style_show_cursor(ctx);```
The nuklear show must be called with a valid context.
If not using the default font, then after a font is initialized and added manually call:
```nk_style_load_all_cursors(ctx, &your_font_atlas);```
And then use the above operations to show the nuklear cursor.
> [nuklear] Added command to enable cursors with default font.

- util/sokol_nuklear.h
Add an option `enable_set_mouse_cursor` to enable setting OS mouse cursors with `sapp_set_mouse_cursor`. By default Nuklear draws its' own custom cursor.
It is the opposite of `disable_set_mouse_cursor` in sokol_imgui.h, to not break existing apps.
Currently this option doesn't actually disable loading the custom cursor icons, and still requires you to call `nk_style_hide_cursor()` to hide Nuklear's cursor.
> sokol_nuklear.h: enable setting mouse cursor

- CHANGELOG.md
- sokol_gfx.h
- util/sokol_gfx_imgui.h
Allows to fetch samples in shader from multisampled textures (for instance to allow custom-resolve render passes).
Not supported on WebGL2/GLES3 because no of missing support for multisampled texture objects, and also not on macOS because it just doesn't seem to work (even though the required function exist, but only in gl3ext.h, not in gl3.h).
Related ticket: https://github.com/floooh/sokol/issues/1142
> sokol_gfx.h: allow multisampled images as resource bindings

- bindgen/gen_odin.py
This affects `intptr_t`, `uintptr_t`, and `size_t`, which are variable-sized. The previous mappings were mapped directly to 64-bit values, and they've been changed to use the corresponding `core:c` aliases.
This closes #1157. An additional fix is required in `sokol-odin` itself to correct `helpers.Allocator.alloc_fn`, which uses `u64` for a `size_t` argument.
> Fix Odin bindgen type mappings

- CHANGELOG.md
- sokol_app.h
Proposal for #1154:
- change `sapp_desc.html5_canvas_name` to `.html5_canvas_selector`
- remove the canvas-id vs canvas-selector hack (instead sokol-app now expects a 'css selector string' to be passed in.
- uses the Emscripten helper function `findCanvasEventTarget()` to lookup the JS canvas name by canvas selector (which also considers `Module['canvas']` and `specialHMTLTargets[]`)
TODO:
To register canvases that can't be looked up via `document.querySelector()`, add them to the `specialHTMLTargets[]` array after the Emscripten environment is setup but before the WASM is started. For instance via `Module.preRun()` in index.html:
```js
preRun: [
() => {
specialHTMLTargets['my_canvas'] = my_canvas;
},
],
```
...then in sokol_main() use `.html5_canvas_selector = "my_canvas"`
> sokol_app.h html5: cleanup canvas lookup handling (see #1154)

- CHANGELOG.md
- util/sokol_imgui.h
Allows to override the C bindings function prefix in sokol_imgui.h via the macro SOKOL_IMGUI_CPREFIX.
> sokol_imgui.h: allow to override the prefix for Dear ImGui C bindings

- sokol_app.h
My library uses Sokol under the hood and requires you to define 
```
add_executable(example WIN32 main.cpp)
target_link_libraries(example MyLib) # MyLib uses Sokol
```
when on Windows by default. If you were to use `add_executable(example main.cpp)` instead, it would not link due to the missing main entrypoint. I could define SOKOL_WIN32_FORCE_MAIN for MyLib to force main(), but then I could not create a WinMain unless I removed it again. I considered doing NO_ENTRY and defining both locally in the library but that seemed like more work (and less in the spirit of open-source) than making a PR.
This PR addresses this problem, creating a definition for `SOKOL_WIN32_FORCE_WINMAIN`. This allows you to force either or both, where the default behaviour is the original behaviour.
- Defining …
> Allow to have both WinMain and main defined on Windows

- CHANGELOG.md
- sokol_gfx.h
- tests/functional/sokol_gfx_test.c
- util/sokol_gfx_imgui.h
- util/sokol_imgui.h
Since Dear ImGui's ImTextureID is now guaranteed to be 64 bits, the sokol-gfx image+sampler pair can now be stashed directly into the ImTextureID instead of requiring a 'backing object'. This simplifies the sokol_imgui.h implementation drastically.
Also: in sokol_gfx.h, add granular `sg_query_buffer_X()` and `sg_query_image_X()` functions which allow to cheaply query buffer and image properties without having to return a big desc struct (might make sense to extend for samplers, but probably less useful for shaders, pipelines and attachments).
TODO:
> sokol_imgui.h: simplify ImTextureID handling.

- CHANGELOG.md
- sokol_app.h
When this is true, sokol_app.h will set the HTML document.title to sapp_desc.window_title.
Fixes #1132
> sokol_app.h html5: new init flag sapp_desc.html5_update_document_title

- bindgen/gen_all.py
- bindgen/gen_d.py
* fix fetch update
* add memtrack
cc: @floooh
**Note**: Tried add `nuklear`, `spine` and `gfx_imgui`, but get struct error!!
```console
ERROR gen_struct: sspine_t * spine;
ERROR gen_struct: sgimgui_buffer_t * slots;
```
> D bindgen: add memtrack and fix fetch update

- sokol_gfx.h
According to PR: https://github.com/webgpu-native/webgpu-headers/pull/324
This can be merged later, when webgpu.h will be updated everywhere.
> [sokol_gfx] add unorm10-10-10-2 vertex format

- bindgen/gen_ir.py
- fix comment ranges being out-of-sync on Windows because of Python's 'new-line normalization' (fixes #1194)
- fix last comment character being omitted (apparently Clang's ranges are inclusive, while Python slices are exclusive)
NOTE: there will almost certainly still be problems with non-ASCII characters in comments, but we don't do that.
> gen_ir.py: comment generation fixes

- CHANGELOG.md
- sokol_gfx.h
This reduces the max occupied storage buffer bindslots in the GL backend from 16 to 8 (same as the max number of storage buffer bindings across all shader stages).
Requires a matching sokol-shdc update (https://github.com/floooh/sokol-tools/pull/170), since previously sokol-shdc would assign fragment shader storage buffer bindings starting at slot 16 (now sokol-shdc simply uses the original binding 0..7).
TODO:
> sokol_gfx.h gl: fix max number of storage buffer bindings (fixes #1193)

- CHANGELOG.md
- sokol_gfx.h
Fixes https://github.com/floooh/sokol/issues/1198
- in sg_make_shader() with the D3D11 backend active, check the HLSL bindslots for valid range, if out-of-range a log error is generated and the shader creation fails with SG_RESOURCESTATE_FAILED
- in the GL backend, make the existing similar bindslot range check non-fatal (instead also fail shader creation with SG_RESOURCESTATE_FAILED)
- fix an unrelated problem that a shader with SG_RESOURCESTATE_FAILED caused a crash in sg_apply_pipeline() in release mode (now the rendering is skipped when trying to apply a pipeline with a shader in SG_RESOURCESTATE_FAILED
TODO:
> sokol_gfx.h: more bindslot range checks in release mode

- sokol_args.h
In Emscripten, the `EM_JS` function should not end with a `;`. This change fixes that for both instances.
This is the error that you get when using the `;`...
```
sokol_args.h:688:63: error: extra ';' outside of a function [-Werror,-Wextra-semi]
688 | EM_JS_DEPS(sokol_audio, "$withStackSave,$stringToUTF8OnStack");
|                                                               ^
sokol_args.h:732:3: error: extra ';' outside of a function [-Werror,-Wextra-semi]
732 | });
|   ^
2 errors generated.
```
> sokol_args: Fix Emscripten extra semi-colon

- CHANGELOG.md
- sokol_app.h
Fix a couple of issues when stealing the window focus via Ctrl-Shift-Esc or Ctrl-Alt-Del:
- handle false return value from GetCursorPos()
- ignore false return valur from SetCursorPos()
- ignore attempt to lock mouse while app window isn't the foreground window
- instead of in WM_KILLFOCUS, poll foreground window status to unlock mouse (e.g. in each frame: if mouse currently locked and window is not the foreground window, unlock the mouse)
> sokol_app.h win32: fix mouse lock edge cases (fixes #1211)

- CHANGELOG.md
- sokol_app.h
See https://github.com/floooh/sokol/issues/1227
> sokol_app.h macos: fix for Ctrl-Tab key down event not sent

- CHANGELOG.md
- sokol_gfx.h
...which protects against calling sg_apply_bindings() with an empty sg_bindings struct.
Related ticket: https://github.com/floooh/sokol/issues/1235
> New validation layer check in sg_apply_bindings()

- sokol_app.h
The handle of X11 Window and Display should be exposed to the end user like every other platform.
This allows doing platform-specific operations such as resizing or setting attributes.
> Expose X11 Window and Display

- util/sokol_imgui.h
The generated binding name for Cimgui has apparently changed. This update should resolve the mismatch issue.
> fix: mismatch function with cimgui

- sokol_app.h
On macOS 15.4.1 `sapp_desc.fullscreen = true` didn't work because `NSWindow -toggleFullScreen:` doesn't seem to work when the `NSApp.activationPolicy` is still `NSApplicationActivationPolicyProhibited`. Setting the activationPolicy earlier fixes the issue. 
(noticed the bug on macOS 15.4.1 (24E263), with SOKOL_METAL, in a command line app, not an app bundle)
Side note: this exposed a bug in `sapp_is_fullscreen` where its internal state could differ from the real window state. To eliminate the possibility of that bug on macOS it could be implemented as 
```c
SOKOL_API_IMPL bool sapp_is_fullscreen(void) {
#if defined(_SAPP_MACOS)
return (_sapp.macos.window.styleMask & NSWindowStyleMaskFullScreen) != 0;
#else
return _sapp.fullscreen;
#endif
}
```
> Set activation policy before making window fullscreen

- CHANGELOG.md
- sokol_gfx.h
All GL backends except macOS now always use glTexStorage + glTexSubImage to create textures, only macOS uses the old-school glTexImage path.
Ticket: https://github.com/floooh/sokol/issues/1263
Test:
> sokol_gfx.h gl: properly separate glTexStorage vs glTexImage code path

- sokol_audio.h
These trigger `-Werror,-Wextra-semi` with clang 19 when building `tests/CMakeLists.txt`:
```
In file included from /home/user/sokol/tests/compile/sokol_audio.c:2:
/home/user/sokol/tests/compile/../../sokol_audio.h:1483:2: error: extra ';' outside of a function [-Werror,-Wextra-semi]
1483 | };
|  ^
/home/user/sokol/tests/compile/../../sokol_audio.h:1492:2: error: extra ';' outside of a function [-Werror,-Wextra-semi]
1492 | };
|  ^
```
> sokol_audio.h: remove extra semicolons

- CHANGELOG.md
- README.md
- util/sokol_gfx_imgui.h
- util/sokol_imgui.h
> Port sokol_imgui.h to Imgui 1.92.0

- sokol_gfx.h
- util/sokol_spine.h
Was looking at some old code I had and noticed the sg_begin_default_pass had been [removed](https://floooh.github.io/2024/02/26/sokol-spring-cleaning-2024.html#detailed-change-list), but there are still a few references to it in the docs.
> remove references to sg_begin_default_pass

- sokol_app.h
mingw gcc don't accept `#pragma comment`, and some warnings would be generated.
```
3rd/sokol/sokol_app.h:2230: warning: ignoring '#pragma comment ' [-Wunknown-pragmas]
2230 |             #pragma comment (linker, "/subsystem:windows")
|
3rd/sokol/sokol_app.h:2236: warning: ignoring '#pragma comment ' [-Wunknown-pragmas]
2236 |     #pragma comment (lib, "kernel32")
|
3rd/sokol/sokol_app.h:2237: warning: ignoring '#pragma comment ' [-Wunknown-pragmas]
2237 |     #pragma comment (lib, "user32")
|
3rd/sokol/sokol_app.h:2238: warning: ignoring '#pragma comment ' [-Wunknown-pragmas]
2238 |     #pragma comment (lib, "shell32")    /* CommandLineToArgvW, DragQueryFileW, DragFinished */
|
3rd/sokol/sokol_app.h:2239: warning: ignoring '#pragma comment ' [-Wunknown-pragmas]
2239 |     #pragma comment …
```
> Avoid warnings in mingw

- CHANGELOG.md
- README.md
- sokol_gfx.h
- util/sokol_gfx_imgui.h
> Implement sg_draw_ex(base_element, num_elements, num_instances, base_vertex, base_instance)

- CHANGELOG.md
- sokol_app.h
Unifies some redundant code from the sokol_app.h macos backend.
Salvaged from an attempt to fix this issue https://github.com/floooh/sokol/issues/1335, which didn't work as intended and needs to be postponed.
> Minor code cleanup in sokol_app.h macos per-frame code.
